@baseUrl = http://127.0.0.1:9901

@teaUrl = {{baseUrl}}/teacher
@stuUrl = http://127.0.0.1:9902/student
@emailUrl = {{baseUrl}}/email
@questionUrl = {{baseUrl}}/question

@token = Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwibmFtZSI6ImFsaWNlOTk5IiwidGVhY2hlciI6dHJ1ZSwiZXhwIjoxNzQyODY0Njg1fQ.ydtbAchC_aAtwHwJr8HI5B5WkVtdXYm-tT6VjG2t92cnp-u858wHm4S4tZ72eFKlAs8YAR4TFlNZfn3g6kLznA


###

# 创建题库
POST {{questionUrl}}/bank HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
    "name" : "sql题库",
    "subject" : "sql"
}

###

# 修改题库
PUT {{questionUrl}}/bank/1 HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
    "name" : "JAVA题库",
    "subject" : "JAVA"
}

###

# 查看题库
GET {{questionUrl}}/bank HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

###

# 查看题库
GET {{questionUrl}}/bank/2 HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

###

# 删除题库
DELETE {{questionUrl}}/bank/3 HTTP/1.1
Content-Type: application/json
Authorization: {{token}}