@baseUrl = http://127.0.0.1:9901
@base2Url = http://127.0.0.1:9902

@teaUrl = {{baseUrl}}/teacher
@stuUrl = {{base2Url}}/student
@emailUrl = {{baseUrl}}/email
@questionUrl = {{baseUrl}}/question
@ansUrl = {{base2Url}}/ans
@paperUrl = {{baseUrl}}/paper

@token = Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwibmFtZSI6ImFsaWNlIiwidGVhY2hlciI6dHJ1ZSwiZXhwIjoxNzQyOTI4MDI2fQ.QjZ6q9ABUuNsOJV4UONaKz0_716KsLDbUe3TfkKVzMmtwWpxDXebM4tJEUK4EShilClEFNmzPkHwqVf7cnqkmQ


###

# 查看试卷
GET {{paperUrl}} HTTP/1.1
Content-Type: application/json
Authorization: {{token}}


###

# 查看试卷题目
GET {{paperUrl}}/1/questions HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

###

# 创建试卷
POST  {{paperUrl}} HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
    "name" : "2025java其中考卷",
    "timeLimit": "120",
    "difficulty": "easy"
}

###

# 添加试卷题目
POST {{paperUrl}}/1/questions HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

[
    {
        "questionId":"3",
        "score":5
    },
    {
        "questionId":"4",
        "score":5
    },
    {
        "questionId":"32",
        "score":5
    }
]
