apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaquiz-deploy
  labels:
    app: javaquiz-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: javaquiz
  template:
    metadata:
      labels:
        app: javaquiz
    spec:
      containers:
        - name: javaquiz
          image: ghcr.io/maidf/javaquiz:v2
          ports:
            - containerPort: 10032
          volumeMounts:
            - name: java-config
              mountPath: /app/config
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
      volumes:
        - name: java-config
          configMap:
            name: java-config
