apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: nginx-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: uniquiz
  template:
    metadata:
      labels:
        app: uniquiz
    spec:
      containers:
        - name: uniquiz
          image: ghcr.io/maidf/uniquiz:v1
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config